# Generated by Django 5.1.4 on 2026-07-02 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('data_export', 'Export de données (SAR)'), ('account_deleted', 'Suppression de compte')], max_length=40)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text="Utilisateur concerné par l'événement.", on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Événement d'audit",
                'verbose_name_plural': "Événements d'audit",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'En cours'), ('responded', 'Répondue'), ('failed', 'Échec')], default='processing', max_length=20)),
                ('requested_format', models.CharField(default='json', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('export_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('export_filename', models.CharField(blank=True, default='', max_length=255)),
                ('response_size', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('requester', models.ForeignKey(help_text="Utilisateur ayant demandé l'export de ses données.", on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'accès aux données (SAR)",
                'verbose_name_plural': "Demandes d'accès aux données (SAR)",
                'ordering': ['-requested_at'],
            },
        ),
    ]
